### PR TITLE
added condition for really simple captcha that gets called twice…

### PR DESCRIPTION
**Pull request by netzgestaltung**
… otherwise - and does not validate

### CODE REVIEW

**Review by aurovrata — APPROVED** [review]
looks good.  I guess the recaptcha plugin is validating once and this was the 2nd call, right?

**Comment by netzgestaltung** [comment]
yes - maybe its also questionable why all fields are gettings a second validation but that was not my topic.

**Comment by aurovrata** [comment]
they are not actually... the CF7 filter "wpcf7_validate_{$type}" is removed when the Smart Grid is activated.  I built this function in order to cross-validate fields, something not possible with CF7 plugin.

You will notice this filter is triggered a few lines down 'cf7sg_validate_submission'  which passes all the submitted data, allowing users to validate a field based on other submitted values.

This is very useful for more complex forms with a lot of data submitted.  I build data analytic tools and this plugin was developed to build a real-time [carbon footprint calculator](https://docs.google.com/presentation/d/1Ye_HZASLyLMSVJ7kQbObaErPlY_SU4GmhtMbvXo72X0/present?token=AC4w5Vgw3_q5LtQGh7WMObX1OoFVy1ydCw%3A1572511630085&includes_info_params=1&eisi=CPmk-KiOxuUCFQe1JAodsWsG7Q#slide=id.p).  Cross-validation was one of the requirements.

Although in the case of the recaptcha, the Really Simple Captcha plugin must be hooking a different filter.

**Comment by aurovrata** [comment]
PS: appreciate the time you took to fix the issue, not always easy to go through someone else's code. 
Feel free to suggest other changes/improvements.

**Comment by netzgestaltung** [comment]
would you mind looking into the other PR so i can update as well?

**Comment by aurovrata** [comment]
I did and it was included in the v2.11.  The PR was accepted and closed, which automatically merges into the master branch and therefore makes it to the next release, did you not see it?

**Pull request merged**
